### ISSUE TITLE
Receive error in events.js when try and move to heroku

### ISSUE THREAD

**Issue by Firexion** [DaftMonk/fullstack-demo#5]
Steps taken:
1. mkdir test
2. cd test
3. yo angular-fullstack
  a. Use Jade, everything else as defaults
4. grunt serve (to confirm everything works locally)
5. yo angular-fullstack:heroku

app is created on heroku but doesn't work and receive the followeing error:

[firexion@firexion-mobile test]$ yo angular-fullstack:heroku
[?] Name to deploy as (Leave blank for a random name): firexion-mean

Initializing deployment repo
Initialized empty Git repository in /home/firexion/Projects/test/dist/.git/

Creating heroku app and setting node environment
Creating firexion-mean... done, stack is cedar

http://firexion-mean.herokuapp.com/ | git@heroku.com:firexion-mean.git

Git remote heroku added

Setting config vars and restarting firexion-mean... 
done, v3

NODE_ENV: production

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at Pipe.onread (net.js:558:19)

**Comment by Firexion** [comment]
meant to put this in the generator-angular-fullstack project.....
